- name: Copy cadvisor files to the server
  template:
    src: "{{ item.src }}"
    dest: "{{ project_dir }}/{{ item.dest }}"
  loop:
    - { src: docker-compose.cadvisor.yml.j2, dest: docker-compose.cadvisor.yml }

- name: Pull new version of cadvisor image
  command: docker compose -f {{ project_dir }}/docker-compose.cadvisor.yml pull
  args:
    chdir: "{{ project_dir }}"

- name: Down cadvisor
  command: docker compose -f {{ project_dir }}/docker-compose.cadvisor.yml down
  args:
    chdir: "{{ project_dir }}"

- name: Run cadvisor
  command: docker compose -f {{ project_dir }}/docker-compose.cadvisor.yml up -d
  args:
    chdir: "{{ project_dir }}"
