pgsql:
    users:
        meteo_station:
            password: ENC[AES256_GCM,data:J/inZv/DtpaaFHwHvLk6EZlJoAc=,iv:sj4HtcEK8QbIKZNNetFZcCeh3cjBuWClvtJjLsjovy8=,tag:LigM/9f7d4L9zQBKMGrqSQ==,type:str]
        postgres:
            password: ENC[AES256_GCM,data:4ERWKYcVJlz6aWUpMxijRKNNVvQ=,iv:v01EhRzAiafJ2++JRLP2PuP4TTthbLJs5uHHxaf06Cg=,tag:CJd9RQ/1vxwtt+l5mwFMqg==,type:str]
image_credentials:
    registry: ENC[AES256_GCM,data:hRdYUluTjQ==,iv:JEsfiZHGYhlHIQd16eeWS7C7mgPnYK5D9InKqF34Ndg=,tag:6l5TqjCu52ufM4P3R8elXA==,type:str]
    username: ENC[AES256_GCM,data:mJFFCIrT,iv:45QiwkCindZe1vsK5pJDchcLtweBMYyE4ZRD5a051e0=,tag:IzsvnNPxhct9PxyD8csUnQ==,type:str]
    password: ENC[AES256_GCM,data:skP6zwcOS3D4nuja10qcWBqcHFLIc97k1+4Cl+Rbx+vTL/b3poAWRg==,iv:ijtu/utCmCfTm/q6cAHJI5BInCXmCRJtif2iBPTGjuw=,tag:+LCQ7CgpScXn8nhNDN03mg==,type:str]
sops:
    age:
        - recipient: age1p3qmgeusy4skc49xy4hjxujm93udxamc0jel2l0phfrrxt8tpcnsksnzu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ2ZqaHZKSk9QUmRObHp5
            S1NUMTN4R000Y1lzTTNKaUZ5TkhXQUorem1FCkhRU0J3R015MWE2UC9nTk4zRXd5
            QkVYakVwRDdrYUl5SVV3clUxNWFEN2sKLS0tIHNaamw2Sk83SWhYVnFQQ1ZsMkxV
            TW95dmd1RTFRYW9EUk0xUmFuT050dHMK2x7JliYAnGXQv1WUnZ2b/wy2aGvXhTPw
            hEjuwWeWJ8+XCfD/6iKvq7dTBYtYtFlK+AQwmw7aYHQdzzXSWkDAFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T21:56:46Z"
    mac: ENC[AES256_GCM,data:aQtTCMVl3XmCKzwOX4WH4y9oCDomrjT7WV0A/NKWfm0m1TWSynff8ovvq/DxcFSuCWv279BUlYZvKzV8OnOPWZdWmGhluKukLKoCFpK7NWptnRZI7l+lRyg8O9y3CM7f6HbcnLoF8WCtirKkS2CaYDNjFg0ogKCqhd/xvqVYMjM=,iv:xPbQG2i2j9MaIDWL6zMH/zHbNFBfdEnPZ52tLTbZIHM=,tag:Z6kdiZENtEeYb1Mpa/f8Pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
