cluster_users:
    - name: ENC[AES256_GCM,data:GXSytTQ9,iv:VvONGkboYrGXULUIuL08cc6DMOosq9EB8fQhzEIHDEw=,tag:nEm5LeE6uQjJ2vSK/yhZmg==,type:str]
      role: ENC[AES256_GCM,data:yrWg2QLvZP1zEjRKhw==,iv:47tzw8zSrcjda3g8njAdGajhD9k6u55+riacaS2oZbk=,tag:InZL3dn292VxW1kU2az2jg==,type:str]
pgsql:
    users:
        meteo_station:
            password: ENC[AES256_GCM,data:6yOwBSzC8dTRV977yEQGsyWvIjg=,iv:30WZCP2wcbpvf0ByvcWvTrFvo+PGmwWpIQ8piNHcDVg=,tag:tPDUa95wc6SFKzmPzOwUzA==,type:str]
        postgres:
            password: ENC[AES256_GCM,data:imAifFoSLqJXfLBfI/DTmBFwMIw=,iv:dc1Qr6ow8A1PhyzUseu8bKRKU+C6CGe4qCDYZKrkNZs=,tag:5HmMIhJhVGW76rPWB3IuGA==,type:str]
        grafana:
            password: ENC[AES256_GCM,data:eL90udek9HCt3fBRIUpMMAy8NBU=,iv:zHWjEfcEjGwukkPp8xssNZ9J7KXO7026hZULnJTCWm8=,tag:4bZMdK5XiXxKo9jKldsR6w==,type:str]
image_credentials:
    registry: ENC[AES256_GCM,data:ATEM6QCWaw==,iv:ENBPZrAwOMEc4TJP2K2pU0nACJMLORiLd0mGQfOmGl0=,tag:QVimLNe54StwebFJsYYSIA==,type:str]
    username: ENC[AES256_GCM,data:oIeTY8KE,iv:6CMELgHlXf8IIxYa8cgESPBO8jOq8YgB1RosYp+9kLw=,tag:G0OEY28Xhyv4jLVR4Tu1tw==,type:str]
    password: ENC[AES256_GCM,data:XTu8T8leAX6cdqZ2nTsnZJxtPY/NeG638BvI6BeTlSH+TPP1lXAamg==,iv:NrcxEe9TMtYVEfTeh+88JQf7QLaIk3JT1OhLvEvZjag=,tag:lxZLABJ0XYTwombQ67G2Xg==,type:str]
grafana:
    adminPassword: ENC[AES256_GCM,data:6TjIHUsY0ehhrS6V0NbuH9pexHs=,iv:xDwFn67mFnnvRU5ey3eKTWloWSctHq+/0pPkE+rQsyY=,tag:ZZRpHm2LkWl4yYldalmxXQ==,type:str]
alertmanager:
    telegram_chat_id: ENC[AES256_GCM,data:/UqKONljcilQeXI=,iv:DId+buN4VKehGGJbtPowwThhhmSyrVGcs5LiiO2OB94=,tag:XkZcAFHGbnn0cdpJwbBa4g==,type:int]
    telegram_topic_id: ENC[AES256_GCM,data:fA==,iv:kReaGvTlO7T/kpLXPbHUwri2gfO15SgGF/+ER+woxK4=,tag:Iay0aas51sI8lCqHiO9CNw==,type:int]
    telegram_token: ENC[AES256_GCM,data:1bwUnDnHfhD6w/GvEK/eYUsQ1ArNPTSpYVqQEbix0SpQI7l3KN6smWgNEVsY+A==,iv:dPiM/3fLU/P6nUZf0U6W6nL/kY8I4bz8BkkYMosyp7g=,tag:23zpqpkIK2bOsh8tWixvtA==,type:str]
mosquitto:
    user: ENC[AES256_GCM,data:kKLFVttZZWzt0zg=,iv:7xmgNIFmUZYBPBISJ6lscqoUEJofendZhCsvgwdUhxA=,tag:x5i+pawHe4taDJBpVwctTA==,type:str]
    password: ENC[AES256_GCM,data:ph5bPh5kMNA=,iv:HU5SuVRQ3H7ZGUzzJLKWx05PK3VHYuQyioRLBjgNI9E=,tag:+Z0XMOtjlgMfsFgGbeh39g==,type:str]
sops:
    age:
        - recipient: age1p3qmgeusy4skc49xy4hjxujm93udxamc0jel2l0phfrrxt8tpcnsksnzu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM3hIcEt6RkNtUExUSUJr
            TThPYkR4NWhZck50R1JmM1hJMEQyQ0FwY1ZFClNFbTBGU3pIZlVJZHlWWGNGaXNP
            d3dDU1BFamFTemFOZVUyanJRUnBzSlEKLS0tIFI5cmdtL3VtZWxHRUROQXNva1Vl
            WXcxc29HR2greXcxNFFFVWNaYVhlZUEKSlJN+Wo/bh/0M4pmrEHsSPwYbPFSuoMG
            GCqUs4pWb4yN+FQGbzTXsGXGeNKcNVSQkq/9cT5RrELwaQQ6eAprQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T20:48:08Z"
    mac: ENC[AES256_GCM,data:E/9Bsv8bvO/d1k7yTJF/uNbAtMdEMmHDF6B9gmUwqOIe3uav0Wi7U6ZSCnRdKesqkBVPphNibaz1E8mrJJ6RtXpN7EIVS2hhvrkO8jSUwvRhpoN7WoB36POYPbYrzIp5IqVDRGEJ4EHExhnUYuC/QAzvnwwh7OKp2z3KZhXZ11A=,iv:rBzV54u/Ma4RZ0pQGLATpz1GaXlg2POsTKSIEjYVYhg=,tag:1pqTYpPKzQsVlQyMXnuEwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
