edit-secrets-pi:
	EDITOR="goland --wait" ansible-vault edit pi/secrets.yml --vault-password-file ../config/.vault_password

edit-secrets-vps:
	EDITOR="goland --wait" ansible-vault edit vps/secrets.yml --vault-password-file ../config/.vault_password
