- name: Copy node_exporter files to the server
  template:
    src: "{{ item.src }}"
    dest: "{{ project_dir }}/{{ item.dest }}"
  loop:
    - { src: docker-compose.node_exporter.yml.j2, dest: docker-compose.node_exporter.yml }

- name: Pull new version of node_exporter image
  command: docker compose -f {{ project_dir }}/docker-compose.node_exporter.yml pull
  args:
    chdir: "{{ project_dir }}"

- name: Down node_exporter
  command: docker compose -f {{ project_dir }}/docker-compose.node_exporter.yml down
  args:
    chdir: "{{ project_dir }}"

- name: Run node_exporter
  command: docker compose -f {{ project_dir }}/docker-compose.node_exporter.yml up -d
  args:
    chdir: "{{ project_dir }}"
