---
- name: Copy grafana files to the server
  template:
    src: "docker-compose.grafana.yml.j2"
    dest: "{{ project_dir }}/docker-compose.grafana.yml"

- name: Pull new version of grafana image
  command: "docker compose -f {{ project_dir }}/docker-compose.grafana.yml pull"
  args:
    chdir: "{{ project_dir }}"

- name: Down grafana
  command: "docker compose -f {{ project_dir }}/docker-compose.grafana.yml down"
  args:
    chdir: "{{ project_dir }}"

- name: Run grafana
  command: "docker compose -f {{ project_dir }}/docker-compose.grafana.yml up -d"
  args:
    chdir: "{{ project_dir }}"
