wifi_ssid: ENC[AES256_GCM,data:BxPN/J9LYf2TSgGZeMOe5OwVMW8lpq8v6LckMiLP4V3AxElLaqCVayQ=,iv:L/PQNR9sQ9VtisOYIzSEwMhXjL8W2CJrNx0g150dAzg=,tag:qCPd3SiAjL7nWvegyBQ4MQ==,type:str]
wifi_password: ENC[AES256_GCM,data:Yq85EPLU1baJ5lU9QlhHNYEGPGYfuM4n3PBobe4oXrUsO3FjxpeYr4VtGPEpo4wUq71Mn4bpCw==,iv:i0Mrayp42rY+2JDlSb5hxoDoebMbp7eTwnBBmOWMcDY=,tag:NgkU/MTNgsjac/1dmKKLzw==,type:str]
api_key: ENC[AES256_GCM,data:rr8FB2/fHLAA1eN67VkPdFweXjDC6UISOs3HHyFCUXUCCoOZ9C89vGiU0W/161VvdrZvD60=,iv:J4vmUwarlcyV0fHEmQ/0hMUyFLVzuL/pxLBKE0dDUuU=,tag:jfZzBI+Ck9UvPsVKqMf2lw==,type:str]
ota_password: ENC[AES256_GCM,data:JCMCdWaTqj/dk/L2N/Zqagg5kz3BUFb01pa3vep2zjJstIUxQaOoaKQro8xclsihMI8=,iv:FqL9itah/KAIvrzCeJ+p18lSaJKuPjvIf+DmK90SeCA=,tag:gwnd5tpgHgM8YL4ZPV8WkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnFib3hCcmRGUzd1L2xO
            MGlKRmJBdHZSNEZuSVBkTFFTOXk4LzNvSDJvCjNkeWJXUm5mRXIwWnZWTEYyZTRB
            MC9HRk93SnRRRHE0RWxHRG94WnNsd0UKLS0tIGxvMFRQZ0p4M2VzRkFLZEU5VXlD
            b1hIdHJoQ25nM1FteEVHV00rWDE1NjgKTNjw0gvv4bMJkaoiskAlSIuGPqcP9MAk
            9yB4vZ0Lm18F4oKtVj18Fp528kCwgGKpgg8zeXv3OhHJm69biliptA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1368fztcpakzx7m9a8kcp7xqjlsjrgvr7sys5llg3jumse5q42q9s7wspuc
    lastmodified: "2026-09-29T14:33:57Z"
    mac: ENC[AES256_GCM,data:kwU3305gLwQuwa/yG++o8m3efYqkn6YMqHMJValIl7myiZJ6epaopxdIGpvJQuvpF+1P06OUsKQMrV7stA1dRjVLgf2w4EKPtjR3v3a/iTm41JfSjc4Hc4x4CKgZS5T/A3ubrCDlVj+cYhClbwfltf3o1kKX8i9rE6BjuUI6wlA=,iv:7C2+teZkaAauNXXLe0BptYBX1/zJjELCBi6KwMgUQaQ=,tag:3SoIQMwAxVUSH1vLoREF2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
