meteo-station ansible_host=31.220.22.18 ansible_port=2002 ansible_user=devops ansible_ssh_private_key_file=~/.ssh/id_rsa_github
monitoring ansible_host=31.220.22.18 ansible_port=2002 ansible_user=devops ansible_ssh_private_key_file=~/.ssh/id_rsa_github
raspberry ansible_host=192.168.1.51 ansible_port=2002 ansible_user=devops ansible_ssh_private_key_file=~/.ssh/id_rsa
