---
- hosts: meteo-station
  become: yes

  vars_files:
    - ../../secrets.yml
    - ../../env.yml
    - env.yml
    - secrets.yml
  tasks:

    - name: Create certs
      import_role:
        name: certs

    - name: Setup project environment
      import_role:
        name: project-environment

    - name: Setup docker
      import_role:
        name: docker

    - name: Setup docker environment
      import_role:
        name: docker-environment

    - name: Setup nginx
      import_role:
        name: nginx
        tasks_from: main.yml

    - name: Update nginx configs
      import_role:
        name: nginx
        tasks_from: update-configs.yml

    - name: Setup postgresql
      import_role:
        name: pgsql

    - name: Setup postgresql dev
      import_role:
        name: pgsql-dev

    - name: Setup mosquitto
      import_role:
        name: mosquitto

    - name: Setup go exporter
      import_role:
        name: go-exporter
