{{- $root := . -}}
{{- range $name, $sec := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "app.fullname" $root) $name }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
type: {{ $sec.type | default "Opaque" }}
{{- with $sec.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: |
    {{- tpl ($value | toString) $root | nindent 4 }}
  {{- end }}
{{- end }}
{{- with $sec.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}