---
- name: Copy prometheus files to the server
  template:
    src: "docker-compose.prometheus.yml.j2"
    dest: "{{ project_dir }}/docker-compose.prometheus.yml"

- name: Pull new version of prometheus image
  command: "docker compose -f {{ project_dir }}/docker-compose.prometheus.yml pull"
  args:
    chdir: "{{ project_dir }}"

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ project_dir }}/prometheus.yml"

- name: Down prometheus
  command: "docker compose -f {{ project_dir }}/docker-compose.prometheus.yml down"
  args:
    chdir: "{{ project_dir }}"

- name: Run prometheus
  command: "docker compose -f {{ project_dir }}/docker-compose.prometheus.yml up -d"
  args:
    chdir: "{{ project_dir }}"
