---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present

- name: Ensure nginx-extras is installed
  apt:
    name: nginx-extras
    state: present

- name: Ensure nginx-full is installed
  apt:
    name: nginx-full
    state: present

- name: Ensure apache2-utils is installed (for htpasswd)
  apt:
    name: apache2-utils
    state: present

- name: Create .htpasswd file
  command: >
    htpasswd -b -c /etc/nginx/.htpasswd {{ basic_auth.username }} {{ basic_auth.password }}
  args:
    creates: /etc/nginx/.htpasswd  # Не создавать файл, если он уже существует

- name: Ensure SSL directory exists
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Ensure stream-available directory exists
  file:
    path: /etc/nginx/stream-available
    state: directory
    mode: '0755'

- name: Ensure stream-enabled directory exists
  file:
    path: /etc/nginx/stream-enabled
    state: directory
    mode: '0755'

#- name: Create symlink for SSL directory
#  file:
#    src: "/etc/letsencrypt/live/{{ main_domain }}/{{ item.file }}"
#    dest:  "/etc/nginx/ssl/{{ item.file }}"
#    state: link
#  loop:
#    - { file: "fullchain.pem" }
#    - { file: "privkey.pem" }

- name: Check NGINX configs
  shell: "/usr/sbin/nginx -t"
  register: nginx_config_status

- name: NGINX test status
  debug:
    msg: "{{ nginx_config_status }}"

- name: Service NGINX reload
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes
  when: nginx_config_status.rc == 0
