- name: Copy home-bridge files to the server
  template:
    src: "{{ item.src }}"
    dest: "{{ project_dir }}/{{ item.dest }}"
  loop:
    - { src: docker-compose.home-bridge.yml.j2, dest: docker-compose.home-bridge.yml }

- name: Pull new version of home-bridge image
  command: docker compose -f {{ project_dir }}/docker-compose.home-bridge.yml pull
  args:
    chdir: "{{ project_dir }}"

- name: Down home-bridge
  command: docker compose -f {{ project_dir }}/docker-compose.home-bridge.yml down
  args:
    chdir: "{{ project_dir }}"

- name: Run home-bridge
  command: docker compose -f {{ project_dir }}/docker-compose.home-bridge.yml up -d
  args:
    chdir: "{{ project_dir }}"
