all:
  vars:
    ansible_port: 2002
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519_bonavi"

  hosts:
    pi:
      ansible_host: 192.168.0.11

    vps:
      ansible_host: coin-1.bonavii.com
      ansible_user: devops
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519_devops_coin"
