---
- name: Copy mosquitto files to the server
  template:
    src: "{{ item.src }}"
    dest: "{{ project_dir }}/{{ item.dest }}"
  loop:
    - { src: docker-compose.mosquitto.yml.j2, dest: docker-compose.mosquitto.yml }

- name: Ensure configuration directory exists
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: '0755'
  loop:
      - { dir: "{{ project_dir }}/mosquitto" }
      - { dir: "{{ project_dir }}/mosquitto/config" }

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ project_dir }}/mosquitto/config/{{ item.dest }}"
  loop:
    - { src: acl.j2, dest: acl }
    - { src: passwd.j2, dest: passwd }
    - { src: mosquitto.conf.j2, dest: mosquitto.conf }

- name: Pull new version of mosquitto image
  command: docker compose -f {{ project_dir }}/docker-compose.mosquitto.yml pull
  args:
    chdir: "{{ project_dir }}"

- name: Down mosquitto
  command: docker compose -f {{ project_dir }}/docker-compose.mosquitto.yml down
  args:
    chdir: "{{ project_dir }}"

- name: Run mosquitto
  command: docker compose -f {{ project_dir }}/docker-compose.mosquitto.yml up -d
  args:
    chdir: "{{ project_dir }}"
