---
- name: Initial server setup
  hosts: pi
  become: yes
  vars:
    ansible_user: bonavi
    ansible_port: 2002
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_bonavi

  roles:
    - role: users
